from structure_classes import FixSupport, Node, Dimension, Frame, PointLoad,DistributedLoad, PinSupport, RollerSupport, Moment, TriangularDistributedLoad, TrapezoidalDistributedLoad, Pin
import os
import random
import cv2 as cv


def main():
    user_path = os.path.expanduser("~")
    desktop_path = os.path.join(user_path, "Desktop")


    # Open a directory in desktop and name it whatever you want and change the name below accordingly
    # For example the code below assumes your directory name as "statics_images"

    dir_name = "statics_images"
    dir_path = os.path.join(desktop_path, dir_name)


    # Either pick a random image or pick a specific one by commenting other line of code

    # filenumber = random.randint(1,17)
    filenumber = 17

    img_name = str(filenumber) + ".png"
    img_path = os.path.join(dir_path, img_name)

    img = cv.imread(img_path)
    cv.imshow("img", img)
    cv.waitKey()

    instances = []
    if filenumber == 1:
        node1 = Node(shape_x=0, shape_y=0, name="A")
        instances.append(node1)
        node2 = Node(shape_x=1, shape_y=0)
        instances.append(node2)
        node3 = Node(shape_x=3, shape_y=0)
        instances.append(node3)
        dim_1 = Dimension(node_1=node1, node_2=node2,value=1,unit="m")
        instances.append(dim_1)
        dim_2 = Dimension(node_1=node2, node_2=node3, value=2, unit="m")
        instances.append(dim_2)
        fs_ins = FixSupport(node=node1)
        instances.append(fs_ins)
        frame_ins_1 = Frame(node1=node1, node2 = node2, direction="horizontal")
        instances.append(frame_ins_1)
        frame_ins_2 = Frame(node1=node2, node2=node3, direction="horizontal")
        instances.append(frame_ins_2)
        pl_ins = PointLoad(node=node2,direction="downward", value=6,unit="kN")
        instances.append(pl_ins)
    elif filenumber == 2:
        node1 = Node(shape_x=0, shape_y=0, name="A")
        instances.append(node1)
        node2 = Node(shape_x=3, shape_y=0)
        instances.append(node2)
        fs_ins = FixSupport(node=node1)
        instances.append(fs_ins)
        frame_ins_1 = Frame(node1=node1, node2=node2, direction="horizontal")
        instances.append(frame_ins_1)
        dim_1 = Dimension(node_1=node1, node_2=node2, value=3, unit="m")
        instances.append(dim_1)
        dl_1 = DistributedLoad(node1=node1,node2=node2,direction="downward",value=4,unit="kN/m")
        instances.append(dl_1)
    elif filenumber == 3:
        node1 = Node(shape_x=0, shape_y=0, name="A")
        instances.append(node1)
        node2 = Node(shape_x=1, shape_y=0)
        instances.append(node2)
        node3 = Node(shape_x=3, shape_y=0, name="B")
        instances.append(node3)
        dim_1 = Dimension(node_1=node1, node_2=node2, value=1, unit="m")
        instances.append(dim_1)
        dim_2 = Dimension(node_1=node2, node_2=node3, value=2, unit="m")
        instances.append(dim_2)
        frame_ins_1 = Frame(node1=node1, node2=node2, direction="horizontal")
        instances.append(frame_ins_1)
        frame_ins_2 = Frame(node1=node2, node2=node3, direction="horizontal")
        instances.append(frame_ins_2)
        pin_sup_1 = PinSupport(node=node1)
        instances.append(pin_sup_1)
        roller_sup_1 = RollerSupport(node=node3)
        instances.append(roller_sup_1)
        pl_ins = PointLoad(node=node2, direction="downward", value=6, unit="kN")
        instances.append(pl_ins)
    elif filenumber == 4:
        node1 = Node(shape_x=0, shape_y=0, name="A")
        instances.append(node1)
        node2 = Node(shape_x=3, shape_y=0, name="B")
        instances.append(node2)
        dim_1 = Dimension(node_1=node1, node_2=node2, value=3, unit="m")
        instances.append(dim_1)
        frame_ins_1 = Frame(node1=node1, node2=node2, direction="horizontal")
        instances.append(frame_ins_1)
        pin_sup_1 = PinSupport(node=node1)
        instances.append(pin_sup_1)
        roller_sup_1 = RollerSupport(node=node2)
        instances.append(roller_sup_1)
        dl_1 = DistributedLoad(node1=node1, node2=node2, direction="downward", value=4, unit="kN/m")
        instances.append(dl_1)
    elif filenumber == 5:
        node1 = Node(shape_x=0, shape_y=0, name="A")
        instances.append(node1)
        node2 = Node(shape_x=1, shape_y=0)
        instances.append(node2)
        node3 = Node(shape_x=3, shape_y=0, name="B")
        instances.append(node3)
        dim_1 = Dimension(node_1=node1, node_2=node2, value=1, unit="m")
        instances.append(dim_1)
        dim_2 = Dimension(node_1=node2, node_2=node3, value=2, unit="m")
        instances.append(dim_2)
        frame_ins_1 = Frame(node1=node1, node2=node2, direction="horizontal")
        instances.append(frame_ins_1)
        frame_ins_2 = Frame(node1=node2, node2=node3, direction="horizontal")
        instances.append(frame_ins_2)
        pin_sup_1 = PinSupport(node=node1)
        instances.append(pin_sup_1)
        roller_sup_1 = RollerSupport(node=node3)
        instances.append(roller_sup_1)
        moment_1 = Moment(node=node2, direction="cw", value=3, unit="kNm")
        instances.append(moment_1)
    elif filenumber == 6:
        node1 = Node(shape_x=0, shape_y=0, name="A")
        instances.append(node1)
        node2 = Node(shape_x=3, shape_y=0, name="B")
        instances.append(node2)
        frame_ins_1 = Frame(node1=node1, node2=node2, direction="horizontal")
        instances.append(frame_ins_1)
        pin_sup_1 = PinSupport(node=node1)
        instances.append(pin_sup_1)
        roller_sup_1 = RollerSupport(node=node2)
        instances.append(roller_sup_1)
        tri_dl_1 = TriangularDistributedLoad(node1=node1, node2=node2,direction="downward", value1=0, value2=2, unit="kN")
        instances.append(tri_dl_1)
    elif filenumber == 7:
        node1 = Node(shape_x=0, shape_y=0, name="A")
        instances.append(node1)
        node2 = Node(shape_x=3, shape_y=0, name="B")
        instances.append(node2)
        frame_ins_1 = Frame(node1=node1, node2=node2, direction="horizontal")
        instances.append(frame_ins_1)
        pin_sup_1 = PinSupport(node=node1)
        instances.append(pin_sup_1)
        roller_sup_1 = RollerSupport(node=node2)
        instances.append(roller_sup_1)
        trap_dl_1 = TrapezoidalDistributedLoad(node1=node1, node2=node2,direction="downward", value1=1, value2=3, unit="kN")
        instances.append(trap_dl_1)
    elif filenumber == 8:
        node1 = Node(shape_x=0, shape_y=0, name="A")
        instances.append(node1)
        node2 = Node(shape_x=1, shape_y=0, name="B")
        instances.append(node2)
        node3 = Node(shape_x=3, shape_y=0, name="C")
        instances.append(node3)
        node4 = Node(shape_x=4, shape_y=0, name="D")
        instances.append(node4)
        node5 = Node(shape_x=5, shape_y=0, name="E")
        instances.append(node5)
        frame_ins_1 = Frame(node1=node1, node2=node4, direction="horizontal")
        instances.append(frame_ins_1)
        frame_ins_2 = Frame(node1=node4, node2=node5, direction="horizontal")
        instances.append(frame_ins_2)
        pin_sup_1 = PinSupport(node=node1)
        instances.append(pin_sup_1)
        roller_sup_1 = RollerSupport(node=node4)
        instances.append(roller_sup_1)
        pl1_ins = PointLoad(node=node2, direction="downward", value=10, unit="kN")
        instances.append(pl1_ins)
        pl2_ins = PointLoad(node=node3, direction="downward", value=20, unit="kN")
        instances.append(pl2_ins)
        pl3_ins = PointLoad(node=node5, direction="downward", value=5, unit="kN")
        instances.append(pl3_ins)
    elif filenumber==9:
        node1 = Node(shape_x=0, shape_y=0, name="A")
        instances.append(node1)
        node2 = Node(shape_x=2, shape_y=0, name="B")
        instances.append(node2)
        node3 = Node(shape_x=3, shape_y=0)
        instances.append(node3)
        node4 = Node(shape_x=4, shape_y=0, name="C")
        instances.append(node4)
        node5 = Node(shape_x=6, shape_y=0, name="D")
        instances.append(node5)
        frame_ins_1 = Frame(node1=node1, node2=node4, direction="horizontal")
        instances.append(frame_ins_1)
        frame_ins_2 = Frame(node1=node4, node2=node5, direction="horizontal")
        instances.append(frame_ins_2)
        pin_sup_1 = PinSupport(node=node1)
        instances.append(pin_sup_1)
        roller_sup_1 = RollerSupport(node=node4)
        instances.append(roller_sup_1)
        pl1_ins = PointLoad(node=node2, direction="downward", value=15, unit="kN")
        instances.append(pl1_ins)
        pl2_ins = PointLoad(node=node5, direction="downward", value=15, unit="kN")
        instances.append(pl2_ins)
        dl_1 = DistributedLoad(node1=node3, node2=node5, direction="downward", value=2, unit="kN/m")
        instances.append(dl_1)
    elif filenumber==10:
        node1 = Node(shape_x=0, shape_y=0)
        instances.append(node1)
        node2 = Node(shape_x=2, shape_y=0, name="D")
        instances.append(node2)
        node3 = Node(shape_x=3, shape_y=0)
        instances.append(node3)
        node4 = Node(shape_x=0, shape_y=6, name="A")
        instances.append(node4)
        node5 = Node(shape_x=2, shape_y=6, name="B")
        instances.append(node5)
        node6 = Node(shape_x=3, shape_y=6, name="C")
        instances.append(node6)
        frame_ins_1 = Frame(node1=node4, node2=node5, direction="horizontal")
        instances.append(frame_ins_1)
        frame_ins_2 = Frame(node1=node5, node2=node6, direction="horizontal")
        instances.append(frame_ins_2)
        frame_ins_3 = Frame(node1=node5, node2=node2, direction="horizontal")
        instances.append(frame_ins_3)
        pin_sup_1 = PinSupport(node=node2)
        instances.append(pin_sup_1)
        pin_sup_2 = PinSupport(node=node5)
        instances.append(pin_sup_2)
        pin_sup_3 = PinSupport(node=node4)
        instances.append(pin_sup_3)
        dl_1 = DistributedLoad(node1=node4, node2=node6, direction="downward", value=9, unit="kN/m")
        instances.append(dl_1)
    elif filenumber==11:
        node1 = Node(shape_x=0, shape_y=0, name="A")
        instances.append(node1)
        node2 = Node(shape_x=3, shape_y=0, name="B")
        instances.append(node2)
        node3 = Node(shape_x=4, shape_y=0)
        instances.append(node3)
        frame_ins_1 = Frame(node1=node1, node2=node2, direction="horizontal")
        instances.append(frame_ins_1)
        frame_ins_2 = Frame(node1=node2, node2=node3, direction="horizontal")
        instances.append(frame_ins_2)
        dl_1 = DistributedLoad(node1=node1, node2=node2, direction="downward", value=4, unit="kN/m")
        instances.append(dl_1)
        pl1_ins = PointLoad(node=node3, direction="downward", value=3, unit="kN")
        instances.append(pl1_ins)
    elif filenumber==12:
        node1 = Node(shape_x=0, shape_y=0, name="A")
        instances.append(node1)
        node2 = Node(shape_x=3, shape_y=0, name="C")
        instances.append(node2)
        node3 = Node(shape_x=5, shape_y=0, name="B")
        instances.append(node3)
        pin_sup_1 = PinSupport(node=node1)
        instances.append(pin_sup_1)
        roller_sup_1 = RollerSupport(node=node3)
        instances.append(roller_sup_1)
        dl_1 = DistributedLoad(node1=node1, node2=node2, direction="downward", value=6, unit="kN/m")
        instances.append(dl_1)
    elif filenumber==13:
        node1 = Node(shape_x=0, shape_y=0, name="A")
        instances.append(node1)
        node2 = Node(shape_x=1.5, shape_y=0, name="C")
        instances.append(node2)
        node3 = Node(shape_x=3, shape_y=0, name="D")
        instances.append(node3)
        node4 = Node(shape_x=6, shape_y=0, name="B")
        instances.append(node4)
        frame_ins_1 = Frame(node1=node1, node2=node2, direction="horizontal")
        instances.append(frame_ins_1)
        frame_ins_2 = Frame(node1=node2, node2=node3, direction="horizontal")
        instances.append(frame_ins_2)
        frame_ins_3 = Frame(node1=node3, node2=node4, direction="horizontal")
        instances.append(frame_ins_3)
        pin_sup_1 = PinSupport(node=node1)
        instances.append(pin_sup_1)
        roller_sup_1 = RollerSupport(node=node4)
        instances.append(roller_sup_1)
        pl1_ins = PointLoad(node=node3, direction="downward", value=5, unit="kN")
        instances.append(pl1_ins)
        tri_dl_1 = TriangularDistributedLoad(node1=node1, node2=node2,direction="downward",value1=3,value2=0,unit="kN/m")
        instances.append(tri_dl_1)
    elif filenumber==14:
        node1 = Node(shape_x=0, shape_y=0, name="A")
        instances.append(node1)
        node2 = Node(shape_x=2, shape_y=0, name="B")
        instances.append(node2)
        node3 = Node(shape_x=4, shape_y=0,name="C")
        instances.append(node3)
        frame_ins_1 = Frame(node1=node1, node2=node3, direction="horizontal")
        instances.append(frame_ins_1)
        dl_1 = DistributedLoad(node1=node2, node2=node3, direction="downward", value=1.5, unit="kN/m")
        instances.append(dl_1)
    elif filenumber == 15:
        node1 = Node(shape_x=0, shape_y=0, name="A")
        instances.append(node1)
        node2 = Node(shape_x=2, shape_y=0)
        instances.append(node2)
        frame_ins_1 = Frame(node1=node1, node2=node2, direction="horizontal")
        instances.append(frame_ins_1)
        dl_1 = DistributedLoad(node1=node1, node2=node2, direction="downward", value=2, unit="kN/m")
        instances.append(dl_1)
        moment_1 = Moment(node=node2, direction="cw", value=6, unit="kNm")
        instances.append(moment_1)
    elif filenumber==16:
        node1 = Node(shape_x=0, shape_y=0)
        instances.append(node1)
        node2 = Node(shape_x=1.5, shape_y=0, name="A")
        instances.append(node2)
        node3 = Node(shape_x=4.5, shape_y=0,name="B")
        instances.append(node3)
        node4 = Node(shape_x=6, shape_y=0)
        instances.append(node4)
        pin_sup_1 = PinSupport(node=node2)
        instances.append(pin_sup_1)
        roller_sup_1 = RollerSupport(node=node3)
        instances.append(roller_sup_1)
        dl_1 = DistributedLoad(node1=node1, node2=node2, direction="downward", value=6, unit="kN/m")
        instances.append(dl_1)
        dl_2 = DistributedLoad(node1=node2, node2=node3, direction="downward", value=9, unit="kN/m")
        instances.append(dl_2)
        dl_3 = DistributedLoad(node1=node2, node2=node3, direction="downward", value=3, unit="kN/m")
        instances.append(dl_3)
    elif filenumber==17:
        node1 = Node(shape_x=0, shape_y=0, name="A")
        instances.append(node1)
        node2 = Node(shape_x=10, shape_y=0, name="B")
        instances.append(node2)
        node3 = Node(shape_x=14, shape_y=0,name="C")
        instances.append(node3)
        node4 = Node(shape_x=18, shape_y=0, name="D")
        instances.append(node4)
        node5 = Node(shape_x=26, shape_y=0, name="E")
        instances.append(node5)
        fix_sup_1 = FixSupport(node=node1)
        instances.append(fix_sup_1)
        roller_sup_1 = RollerSupport(node=node3)
        instances.append(roller_sup_1)
        roller_sup_2 = RollerSupport(node=node5)
        instances.append(roller_sup_2)
        pin_1 = Pin(node=node2)
        instances.append(pin_1)
        pin_2 = Pin(node=node4)
        instances.append(pin_2)
        dl_1 = DistributedLoad(node1=node1, node2=node2, direction="downward", value=10, unit="kips/ft")
        instances.append(dl_1)
        dl_2 = DistributedLoad(node1=node2, node2=node3, direction="downward", value=10, unit="kips/ft")
        instances.append(dl_2)
        dl_3 = DistributedLoad(node1=node3, node2=node4, direction="downward", value=10, unit="kips/ft")
        instances.append(dl_3)
        dl_4 = DistributedLoad(node1=node4, node2=node5, direction="downward", value=10, unit="kips/ft")
        instances.append(dl_4)
if __name__ == '__main__':
    main()